### PR TITLE
Address compilation failure with Clang -std=c++20.

### PR DESCRIPTION
**Pull request by jyknight**
In C++20, vector became constexpr. Somehow, this causes the calls to `sub_nodes.emplace_back` to trigger an error from the attempt to convert `unique_ptr<MatmulNode>` (and others) to `unique_ptr<INode>`, when `MatmulNode` is an incomplete type.

It seems like that _should_ have been an error before as well, since that conversion is only valid if `MatmulNode` is known to be a subtype of INode. But, I suppose previously it was deferred until after `matmul.h` had been included, and now due to constexpr the conversion attempt is triggered eagerly.

To resolve, put the definitions of the functions in the headers associated with each type.

### CODE REVIEW

**Comment by jyknight** [comment]
Example error message:
```
In file included from cudnn-frontend/samples/cpp/mha.cpp:23:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/catch_test_macros.hpp:11:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/internal/catch_test_macro_impl.hpp:12:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/internal/catch_assertion_handler.hpp:11:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/catch_assertion_info.hpp:13:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/internal/catch_stringref.hpp:12:
In file included from /usr/include/c++/v1/string:554:
In file included from /usr/include/c++/v1/__memory/allocate_at_least.h:13:
/usr/include/c++/v1/__memory/allocator_traits.h:304:9: error: no matching function for call to 'construct_at'
  304 |         _VSTD::construct_at(__p, _VSTD::forward<_Args>(__args)...);
      |         ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/__config:667:17: note: expanded from macro '_VSTD'
  667 | #  define _VSTD std
      |                 ^
/usr/include/c++/v1/vector:933:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::shared_ptr<cudnn_frontend::graph::INode>>>::construct<std::shared_ptr<cudnn_frontend::graph::INode>, std::unique_ptr<cudnn_frontend::graph::MatmulNode>, void, void>' requested here
  933 |     __alloc_traits::construct(this->__alloc(), std::__to_address(__tx.__pos_),
      |                     ^
/usr/include/c++/v1/vector:1706:9: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::__construct_one_at_end<std::unique_ptr<cudnn_frontend::graph::MatmulNode>>' requested here
 1706 |         __construct_one_at_end(std::forward<_Args>(__args)...);
      |         ^
cudnn-frontend/include/cudnn_frontend/node/../node_interface.h:176:19: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::emplace_back<std::unique_ptr<cudnn_frontend::graph::MatmulNode>>' requested here
  176 |         sub_nodes.emplace_back(std::make_unique<MatmulNode>(std::move(attributes), context));
      |                   ^
/usr/include/c++/v1/__memory/construct_at.h:36:38: note: candidate template ignored: substitution failure [with _Tp = std::shared_ptr<cudnn_frontend::graph::INode>, _Args = <std::unique_ptr<cudnn_frontend::graph::MatmulNode>>]: no matching constructor for initialization of 'std::shared_ptr<cudnn_frontend::graph::INode>'
   35 | template <class _Tp, class... _Args, class = decltype(::new(std::declval<void*>()) _Tp(std::declval<_Args>()...))>
      |                                                                                    ~~~
   36 | _LIBCPP_HIDE_FROM_ABI constexpr _Tp* construct_at(_Tp* __location, _Args&&... __args) {
      |                                      ^
In file included from cudnn-frontend/samples/cpp/mha.cpp:23:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/catch_test_macros.hpp:11:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/internal/catch_test_macro_impl.hpp:12:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/internal/catch_assertion_handler.hpp:11:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/catch_assertion_info.hpp:13:
In file included from cudnn-frontend/build/_deps/catch2-src/src/catch2/../catch2/internal/catch_stringref.hpp:12:
In file included from /usr/include/c++/v1/string:554:
In file included from /usr/include/c++/v1/__memory/allocate_at_least.h:13:
/usr/include/c++/v1/__memory/allocator_traits.h:304:9: error: no matching function for call to 'construct_at'
  304 |         _VSTD::construct_at(__p, _VSTD::forward<_Args>(__args)...);
      |         ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/__config:667:17: note: expanded from macro '_VSTD'
  667 | #  define _VSTD std
      |                 ^
/usr/include/c++/v1/vector:933:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::shared_ptr<cudnn_frontend::graph::INode>>>::construct<std::shared_ptr<cudnn_frontend::graph::INode>, std::unique_ptr<cudnn_frontend::graph::SoftmaxNode>, void, void>' requested here
  933 |     __alloc_traits::construct(this->__alloc(), std::__to_address(__tx.__pos_),
      |                     ^
/usr/include/c++/v1/vector:1706:9: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::__construct_one_at_end<std::unique_ptr<cudnn_frontend::graph::SoftmaxNode>>' requested here
 1706 |         __construct_one_at_end(std::forward<_Args>(__args)...);
      |         ^
cudnn-frontend/include/cudnn_frontend/node/../node_interface.h:187:19: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::emplace_back<std::unique_ptr<cudnn_frontend::graph::SoftmaxNode>>' requested here
  187 |         sub_nodes.emplace_back(std::make_unique<SoftmaxNode>(std::move(attributes), context));
      |                   ^
/usr/include/c++/v1/__memory/construct_at.h:36:38: note: candidate template ignored: substitution failure [with _Tp = std::shared_ptr<cudnn_frontend::graph::INode>, _Args = <std::unique_ptr<cudnn_frontend::graph::SoftmaxNode>>]: no matching constructor for initialization of 'std::shared_ptr<cudnn_frontend::graph::INode>'
   35 | template <class _Tp, class... _Args, class = decltype(::new(std::declval<void*>()) _Tp(std::declval<_Args>()...))>
      |                                                                                    ~~~
   36 | _LIBCPP_HIDE_FROM_ABI constexpr _Tp* construct_at(_Tp* __location, _Args&&... __args) {
      |                                      ^
```

**Comment by Anerudhan** [comment]
Hi @jyknight ,

Thanks for reporting this!!

We tried with both clang-14 and clang-17, with cxx-20 in the CMakeLists.txt and are unable to reproduce the error. 

Can you let us know which clang version is causing this error?

Thanks,
Anerudhan

**Comment by mnicely** [comment]
@jyknight are you able to provide the clang version you're using?

**Comment by ilya-biryukov** [comment]
This should reproduce at least with Clang 16, Clang 17 and Clang 18 in C++20 mode and **a fresh version of libc++ or libstdc++**. 
Could it be that the standard library the Clang used when you tried did not have full C++20 support? (By default Clang will use libstdc++ installed in the system, I'm not sure which minimal version we need to reproduce it).

To illustrate the problem, here is a compiler explorer link that shows a similar pattern that causes problems in `-std=c++20` for Clang, but not for `-std=c++17`: https://gcc.godbolt.org/z/5b6Pdxsjd.

This patch does solve a real miscompile on newer versions of Clang with latest libc++ and libstdc++ and with `-std=c++20` enabled.

**Comment by ilya-biryukov** [comment]
This should reproduce at least with Clang 16, Clang 17 and Clang 18 in C++20 mode and **a fresh version of libc++ or libstdc++**. 
Could it be that the standard library the Clang used when you tried did not have full C++20 support? (By default Clang will use libstdc++ installed in the system, I'm not sure which minimal version we need to reproduce it).

To illustrate the problem, here is a compiler explorer link that shows a similar pattern that causes problems in `-std=c++20` for Clang, but not for `-std=c++17`: https://gcc.godbolt.org/z/5b6Pdxsjd.

This patch does solve a real miscompile on newer versions of Clang with latest libc++ and libstdc++ and with `-std=c++20` enabled.

**Pull request merged**
